---
- name: Install and configure Apache2
  hosts: webservers
  become: true

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Allow Apache through the firewall
      ufw:
        rule: allow
        name: 'Apache Full'
